channels:
- conda-forge
dependencies:
- python=3.10.5
- pip<=26.0.1
- pip:
  - mlflow==2.13.2
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.3.0
  - psutil==7.0.0
  - pyyaml==6.0.2
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
